name = "hello_world"

[applications]

[applications.rust]
type = "Functions"
wasm_path = "oak_functions/examples/bin/hello_world.wasm"
target = { Cargo = { cargo_manifest = "oak_functions/examples/hello_world/module/Cargo.toml" } }

[server]
additional_args = [
  "--config-path=./oak_functions/examples/hello_world/config.toml"
]

[clients]
rust = { Cargo = { cargo_manifest = "oak_functions/examples/hello_world/client/rust/Cargo.toml" }, additional_args = [
  "--uri=http://localhost:8080"
] }
java = { Bazel = { bazel_target = "//oak_functions/examples/hello_world/client/java:client" } }
