[package]
name = "oak_remote_attestation_noninteractive"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
futures-util = "*"
prost = "*"
tink-aead = "*"
tink-core = "*"
tink-hybrid = "*"
tink-proto = "*"
tonic = "*"

[build-dependencies]
oak_grpc_utils = { path = "../oak_grpc_utils" }

[dev-dependencies]
assert_matches = "*"
