#!/usr/bin/env bash

readonly SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
# shellcheck source=scripts/common
source "$SCRIPTS_DIR/common"

COMPILATION_MODE='fastbuild'
STRIP='sometimes'

while getopts "hd" opt; do
    case "$opt" in
    h)
        echo -e "Usage: $0 [-d]
  -d    Build using debug mode
  -h    Print this message"
        exit 0
        ;;
    d)
        COMPILATION_MODE='dbg'
        STRIP='never'
        ;;
    *)
        exit 1
        ;;
    esac
done

bazel_build_flags+=(
    '--config=clang'
    "--compilation_mode=$COMPILATION_MODE"
    "--strip=$STRIP"
)

# Use a different output_base so that we don't lose incremental state.
# See https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_base.
bazel --output_base="$CACHE_DIR/clang" build "${bazel_build_flags[@]}" //oak/server/dev:oak
